apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
