{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "database-load.fullname" . }}-archive-pv
  labels:
    {{- include "database-load.labels" . | nindent 4 }}
    volume-type: archive
spec:
  capacity:
    storage: {{ .Values.persistence.archive.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName }}
  hostPath:
    path: {{ .Values.persistence.archive.hostPath }}
    type: DirectoryOrCreate
{{- end }}
