{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "database-load.fullname" . }}-coupon-files-pv
  labels:
    {{- include "database-load.labels" . | nindent 4 }}
    volume-type: coupon-files
spec:
  capacity:
    storage: {{ .Values.persistence.couponFiles.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName }}
  hostPath:
    path: {{ .Values.persistence.couponFiles.hostPath }}
    type: DirectoryOrCreate
{{- end }}
